create type "public"."auction_status" as enum ('Active', 'Pending', 'Completed');

create type "public"."review_type" as enum ('Auctineer', 'Contractor');

create table "public"."Review" (
    "id" bigint generated by default as identity not null,
    "reviewer_id" uuid not null,
    "reviewee_id" uuid not null,
    "auction_id" uuid not null,
    "content" text default ''::text,
    "rating" real not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone,
    "deleted_at" timestamp with time zone,
    "type" review_type not null
);


alter table "public"."Auction" drop column "active";

alter table "public"."Auction" add column "status" auction_status default 'Active'::auction_status;

CREATE UNIQUE INDEX "Review_pkey" ON public."Review" USING btree (id);

alter table "public"."Review" add constraint "Review_pkey" PRIMARY KEY using index "Review_pkey";

alter table "public"."Review" add constraint "Review_auction_id_fkey" FOREIGN KEY (auction_id) REFERENCES "Auction"(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."Review" validate constraint "Review_auction_id_fkey";

alter table "public"."Review" add constraint "Review_reviewee_id_fkey" FOREIGN KEY (reviewee_id) REFERENCES "AuctionHausUsers"(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."Review" validate constraint "Review_reviewee_id_fkey";

alter table "public"."Review" add constraint "Review_reviewer_id_fkey" FOREIGN KEY (reviewer_id) REFERENCES "AuctionHausUsers"(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."Review" validate constraint "Review_reviewer_id_fkey";

grant delete on table "public"."Review" to "anon";

grant insert on table "public"."Review" to "anon";

grant references on table "public"."Review" to "anon";

grant select on table "public"."Review" to "anon";

grant trigger on table "public"."Review" to "anon";

grant truncate on table "public"."Review" to "anon";

grant update on table "public"."Review" to "anon";

grant delete on table "public"."Review" to "authenticated";

grant insert on table "public"."Review" to "authenticated";

grant references on table "public"."Review" to "authenticated";

grant select on table "public"."Review" to "authenticated";

grant trigger on table "public"."Review" to "authenticated";

grant truncate on table "public"."Review" to "authenticated";

grant update on table "public"."Review" to "authenticated";

grant delete on table "public"."Review" to "service_role";

grant insert on table "public"."Review" to "service_role";

grant references on table "public"."Review" to "service_role";

grant select on table "public"."Review" to "service_role";

grant trigger on table "public"."Review" to "service_role";

grant truncate on table "public"."Review" to "service_role";

grant update on table "public"."Review" to "service_role";